# Lista de nombres de tokens
tokens = [
    # Palabras clave
    'ENTERO', 'FLOTANTE', 'STRING', 'IF', 'WHILE', 'RETURN', 'NULL', 'BREAK',
    'SWITCH', 'CASE', 'DEFAULT', 'ARRAY', 'PRINT', 'CHAR', 'ELSE', 'TRUE', 'FALSE',

    # Números hexadecimales
    'HEX_0', 'HEX_1', 'HEX_2', 'HEX_3', 'HEX_4', 'HEX_5', 'HEX_6', 'HEX_7',
    'HEX_8', 'HEX_9', 'HEX_A', 'HEX_B', 'HEX_C', 'HEX_D', 'HEX_E', 'HEX_F',

    # Caracteres (solo algunos representativos, la lista completa sería muy larga)
    'NULL_CHAR', 'SOH_CHAR', 'STX_CHAR', 'ETX_CHAR', 'EOT_CHAR', 'ENQ_CHAR', 'ACK_CHAR',
    'BEL_CHAR', 'BS_CHAR', 'HT_CHAR', 'LF_CHAR', 'VT_CHAR', 'FF_CHAR', 'CR_CHAR', 'SO_CHAR',
    'SI_CHAR', 'DLE_CHAR', 'DC1_CHAR', 'DC2_CHAR', 'DC3_CHAR', 'DC4_CHAR', 'NAK_CHAR', 'SYN_CHAR',
    'ETB_CHAR', 'CAN_CHAR', 'EM_CHAR', 'SUB_CHAR', 'ESC_CHAR', 'FS_CHAR', 'GS_CHAR', 'RS_CHAR',
    'US_CHAR', 'SPACE_CHAR', 'EXCLAMATION_CHAR', 'DOUBLE_QUOTE_CHAR', 'HASH_CHAR', 'DOLLAR_CHAR',
    'PERCENT_CHAR', 'AMPERSAND_CHAR', 'SINGLE_QUOTE_CHAR', 'LPAREN_CHAR', 'RPAREN_CHAR', 'ASTERISK_CHAR',
    'PLUS_CHAR', 'COMMA_CHAR', 'MINUS_CHAR', 'DOT_CHAR', 'SLASH_CHAR', 'ZERO_CHAR', 'ONE_CHAR',
    'TWO_CHAR', 'THREE_CHAR', 'FOUR_CHAR', 'FIVE_CHAR', 'SIX_CHAR', 'SEVEN_CHAR', 'EIGHT_CHAR',
    'NINE_CHAR', 'COLON_CHAR', 'SEMICOLON_CHAR', 'LESS_THAN_CHAR', 'EQUALS_CHAR', 'GREATER_THAN_CHAR',
    'QUESTION_MARK_CHAR', 'AT_CHAR', 'A_CHAR', 'B_CHAR', 'C_CHAR', 'D_CHAR', 'E_CHAR', 'F_CHAR',
    'G_CHAR', 'H_CHAR', 'I_CHAR', 'J_CHAR', 'K_CHAR', 'L_CHAR', 'M_CHAR', 'N_CHAR', 'O_CHAR',
    'P_CHAR', 'Q_CHAR', 'R_CHAR', 'S_CHAR', 'T_CHAR', 'U_CHAR', 'V_CHAR', 'W_CHAR', 'X_CHAR',
    'Y_CHAR', 'Z_CHAR', 'LBRACKET_CHAR', 'BACKSLASH_CHAR', 'RBRACKET_CHAR', 'CARET_CHAR', 'UNDERSCORE_CHAR',
    'BACKTICK_CHAR', 'a_CHAR', 'b_CHAR', 'c_CHAR', 'd_CHAR', 'e_CHAR', 'f_CHAR', 'g_CHAR', 'h_CHAR',
    'i_CHAR', 'j_CHAR', 'k_CHAR', 'l_CHAR', 'm_CHAR', 'n_CHAR',      'o_CHAR', 'p_CHAR', 'q_CHAR',
    'r_CHAR', 's_CHAR', 't_CHAR', 'u_CHAR', 'v_CHAR', 'w_CHAR', 'x_CHAR', 'y_CHAR', 'z_CHAR', 'LBRACE_CHAR',
    'PIPE_CHAR', 'RBRACE_CHAR', 'TILDE_CHAR', 'SUPR_CHAR', 'CEDILLA_UPPER_CHAR', 'UMLAUT_LOWER_u_CHAR',
    'ACUTE_LOWER_e_CHAR', 'CIRCUMFLEX_LOWER_a_CHAR', 'UMLAUT_LOWER_a_CHAR', 'GRAVE_LOWER_a_CHAR',
    'RING_LOWER_a_CHAR', 'CEDILLA_LOWER_c_CHAR', 'CIRCUMFLEX_LOWER_e_CHAR', 'UMLAUT_LOWER_e_CHAR',
    'GRAVE_LOWER_e_CHAR', 'UMLAUT_LOWER_i_CHAR', 'CIRCUMFLEX_LOWER_i_CHAR', 'GRAVE_LOWER_i_CHAR',
    'UMLAUT_UPPER_A_CHAR', 'RING_UPPER_A_CHAR', 'ACUTE_UPPER_E_CHAR', 'DIPHTHONG_LOWER_ae_CHAR',
    'DIPHTHONG_UPPER_AE_CHAR', 'CIRCUMFLEX_LOWER_o_CHAR', 'UMLAUT_LOWER_o_CHAR', 'GRAVE_LOWER_o_CHAR',
    'CIRCUMFLEX_LOWER_u_CHAR', 'GRAVE_LOWER_u_CHAR', 'UMLAUT_LOWER_y_CHAR', 'UMLAUT_UPPER_O_CHAR',
    'UMLAUT_UPPER_U_CHAR', 'SLASH_LOWER_o_CHAR', 'POUND_SIGN_CHAR', 'SLASH_UPPER_O_CHAR', 'MULTIPLICATION_SIGN_CHAR',
    'FLORIN_CHAR', 'ACUTE_LOWER_a_CHAR', 'ACUTE_LOWER_i_CHAR', 'ACUTE_LOWER_o_CHAR', 'ACUTE_LOWER_u_CHAR',
    'TILDE_LOWER_n_CHAR', 'TILDE_UPPER_N_CHAR', 'ORDINAL_FEMININE_CHAR', 'ORDINAL_MASCULINE_CHAR',
    'INVERTED_QUESTION_MARK_CHAR', 'REGISTERED_SIGN_CHAR', 'NOT_SIGN_CHAR', 'HALF_CHAR', 'QUARTER_CHAR', 
    'INVERTED_EXCLAMATION_MARK_CHAR', 'LEFT_ANGLE_QUOTE_CHAR', 'RIGHT_ANGLE_QUOTE_CHAR', 'LOW_DENSITY_SHADE_CHAR', 
    'MEDIUM_DENSITY_SHADE_CHAR', 'HIGH_DENSITY_SHADE_CHAR', 'VERTICAL_BAR_CHAR', 'RIGHT_TEE_CHAR', 'ACUTE_UPPER_A_CHAR',
    'CIRCUMFLEX_UPPER_A_CHAR', 'GRAVE_UPPER_A_CHAR', 'COPYRIGHT_SIGN_CHAR', 'DOUBLE_VERTICAL_LINE_CHAR',
    'DOUBLE_VERTICAL_BAR_CHAR', 'TOP_RIGHT_CORNER_CHAR', 'BOTTOM_RIGHT_DOUBLE_CORNER_CHAR', 'CENT_SIGN_CHAR', 'YEN_SIGN_CHAR',
    'TOP_LEFT_CORNER_CHAR', 'BOTTOM_LEFT_CORNER_CHAR', 'BOTTOM_TEE_CHAR', 'TOP_TEE_CHAR', 'LEFT_TEE_CHAR',
    'HORIZONTAL_BAR_CHAR', 'CROSS_CHAR', 'TILDE_LOWER_a_CHAR', 'TILDE_UPPER_A_CHAR', 'BOTTOM_LEFT_DOUBLE_CORNER_CHAR',
    'TOP_LEFT_DOUBLE_CORNER_CHAR', 'BOTTOM_DOUBLE_TEE_CHAR', 'TOP_DOUBLE_TEE_CHAR', 'RIGHT_DOUBLE_TEE_CHAR',
    'DOUBLE_HORIZONTAL_BAR_CHAR', 'CROSS_DOUBLE_LINES_CHAR', 'CURRENCY_SIGN_CHAR', 'ETH_LOWER_CHAR', 'ETH_UPPER_CHAR',
    'CIRCUMFLEX_UPPER_E_CHAR', 'UMLAUT_UPPER_E_CHAR', 'GRAVE_UPPER_E_CHAR', 'DOTLESS_LOWER_I_CHAR', 'ACUTE_UPPER_I_CHAR',
    'CIRCUMFLEX_UPPER_I_CHAR', 'UMLAUT_UPPER_I_CHAR', 'BOTTOM_RIGHT_CORNER_CHAR', 'TOP_LEFT_CORNER_SIMPLE_CHAR',
    'FULL_BLOCK_CHAR', 'LOW_HALF_BLOCK_CHAR', 'BROKEN_BAR_CHAR', 'GRAVE_UPPER_I_CHAR', 'UPPER_HALF_BLOCK_CHAR',
    'ACUTE_UPPER_O_CHAR', 'ESZETT_CHAR', 'CIRCUMFLEX_UPPER_O_CHAR', 'GRAVE_UPPER_O_CHAR', 'TILDE_LOWER_o_CHAR',
    'TILDE_UPPER_O_CHAR', 'MICRO_SIGN_CHAR', 'THORN_LOWER_CHAR', 'THORN_UPPER_CHAR', 'ACUTE_UPPER_U_CHAR',
    'CIRCUMFLEX_UPPER_U_CHAR', 'GRAVE_UPPER_U_CHAR', 'ACUTE_LOWER_y_CHAR', 'ACUTE_UPPER_Y_CHAR', 'MACRON_CHAR',
    'ACUTE_SIGN_CHAR', 'CONGRUENCE_SIGN_CHAR', 'PLUS_MINUS_SIGN_CHAR', 'DOUBLE_LOW_LINE_CHAR', 'THREE_QUARTERS_CHAR',
    'PILCROW_SIGN_CHAR', 'SECTION_SIGN_CHAR', 'DIVISION_SIGN_CHAR', 'CEDILLA_SIGN_CHAR', 'DEGREE_SIGN_CHAR',
    'DIAERESIS_SIGN_CHAR', 'MIDDLE_DOT_CHAR', 'SUPERSCRIPT_ONE_CHAR', 'SUPERSCRIPT_THREE_CHAR', 'SUPERSCRIPT_TWO_CHAR',
    'BLACK_SQUARE_CHAR', 'NO_BREAK_SPACE_CHAR',

    # Operadores
    'PLUS_OP', 'MINUS_OP', 'MULT_OP', 'DIV_OP', 'ASSIGN_OP', 'EQ_OP', 'MORE_OP', 'LESS_OP', 'NE_OP',

    # Símbolos especiales
    'LPAREN_SPEC', 'RPAREN_SPEC', 'SEMICOLON_SPEC', 'LBRACE_SPEC', 'RBRACE_SPEC',
    'LBRACKET_SPEC', 'RBRACKET_SPEC',

    # Identificadores
    'IDENTIFIER'
]
